on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          "echo Job ${{ github.job }}"
          npm install
          npm run build
          working-directory: ./temp
          shell: bash
          |

      - run: print %ENV
        shell: perl {0}


